import 'dart:convert';
import 'dart:io';
import 'dart:math';
import 'dart:typed_data';

import 'package:path_provider/path_provider.dart';

import '../domain/document_media_store.dart';

export '../domain/document_media_store.dart';

/// Persists validated desktop-editor images below application support storage.
///
/// Files are stored under `documents/media/<encoded-document-id>/`. Every
/// target name is generated by this class, so neither a user file name nor a
/// document ID can become a filesystem path segment.
final class LocalDocumentMediaStore implements DocumentMediaStore {
  LocalDocumentMediaStore({
    Future<Directory> Function()? supportDirectory,
    this.maximumImageBytes = defaultMaximumImageBytes,
    this.assetIdGenerator,
  }) : _supportDirectory = supportDirectory ?? getApplicationSupportDirectory {
    if (maximumImageBytes <= 0) {
      throw ArgumentError.value(
        maximumImageBytes,
        'maximumImageBytes',
        'must be greater than zero',
      );
    }
  }

  static const String uriScheme = DocumentMediaUri.scheme;
  static const int defaultMaximumImageBytes = 20 * 1024 * 1024;
  static const int _maximumDocumentIdBytes = 128;
  static final RegExp _assetIdPattern = RegExp(r'^[A-Za-z0-9_-]{16,64}$');

  static const List<_ImageFormat> _imageFormats = <_ImageFormat>[
    _ImageFormat(extension: 'png', mimeType: 'image/png'),
    _ImageFormat(extension: 'jpg', mimeType: 'image/jpeg'),
    _ImageFormat(extension: 'gif', mimeType: 'image/gif'),
    _ImageFormat(extension: 'webp', mimeType: 'image/webp'),
  ];

  final Future<Directory> Function() _supportDirectory;
  final int maximumImageBytes;
  final String Function()? assetIdGenerator;

  /// Returns a parsed, well-formed Huahuo media URI, or null for any other
  /// scheme, host, path shape, query, or fragment.
  static Uri? parseUri(String value) => DocumentMediaUri.parse(value);

  static bool isHuahuoMediaUri(Uri uri) => DocumentMediaUri.isValid(uri);

  @override
  Future<LocalDocumentMediaAsset> importFile({
    required String documentId,
    required File source,
    String? mimeType,
  }) async {
    if (!await source.exists()) {
      throw const LocalDocumentMediaException(
        'The selected image no longer exists.',
      );
    }
    final length = await source.length();
    if (length > maximumImageBytes) {
      throw LocalDocumentMediaException(
        'The selected image exceeds the $maximumImageBytes-byte limit.',
      );
    }
    return importBytes(
      documentId: documentId,
      bytes: await source.readAsBytes(),
      fileName: _fileNameForPath(source.path),
      mimeType: mimeType,
    );
  }

  @override
  Future<LocalDocumentMediaAsset> importBytes({
    required String documentId,
    required Uint8List bytes,
    required String fileName,
    String? mimeType,
  }) async {
    final normalizedDocumentId = _normalizeDocumentId(documentId);
    final format = _validateImport(
      bytes: bytes,
      fileName: fileName,
      mimeType: mimeType,
    );
    final directory = await _ensureMediaDirectory(normalizedDocumentId);

    for (var attempt = 0; attempt < 8; attempt += 1) {
      final assetId = _nextAssetId();
      final target = File(
        _childPath(directory.path, '$assetId.${format.extension}'),
      );
      final targetType = await FileSystemEntity.type(
        target.path,
        followLinks: false,
      );
      if (targetType != FileSystemEntityType.notFound) continue;

      final temporary = File(
        _childPath(
          directory.path,
          '.$assetId.${_nextRandomId()}.${format.extension}.tmp',
        ),
      );
      try {
        await temporary.writeAsBytes(bytes, flush: true);
        await temporary.rename(target.path);
      } on FileSystemException {
        if (await temporary.exists()) {
          await temporary.delete();
        }
        if (await FileSystemEntity.type(target.path, followLinks: false) !=
            FileSystemEntityType.notFound) {
          continue;
        }
        rethrow;
      }

      return LocalDocumentMediaAsset(
        documentId: normalizedDocumentId,
        assetId: assetId,
        uri: DocumentMediaUri.forAsset(assetId),
        mimeType: format.mimeType,
        extension: format.extension,
        byteLength: bytes.length,
      );
    }

    throw const LocalDocumentMediaException(
      'Could not allocate a unique local image identifier.',
    );
  }

  @override
  Future<LocalDocumentMediaData?> read({
    required String documentId,
    required Uri uri,
  }) async {
    final resolved = await _resolve(documentId: documentId, uri: uri);
    if (resolved == null) return null;
    return LocalDocumentMediaData(
      asset: resolved.asset,
      bytes: Uint8List.fromList(resolved.bytes),
    );
  }

  @override
  Future<File?> resolveFile({
    required String documentId,
    required Uri uri,
  }) async {
    final resolved = await _resolve(documentId: documentId, uri: uri);
    return resolved?.file;
  }

  @override
  Future<bool> delete({required String documentId, required Uri uri}) async {
    final assetId = DocumentMediaUri.assetId(uri);
    if (assetId == null) return false;

    final directory = await _existingMediaDirectory(
      _normalizeDocumentId(documentId),
    );
    if (directory == null) return false;

    var deleted = false;
    for (final format in _imageFormats) {
      final target = File(
        _childPath(directory.path, '$assetId.${format.extension}'),
      );
      final type = await FileSystemEntity.type(target.path, followLinks: false);
      if (type == FileSystemEntityType.notFound) continue;
      if (type != FileSystemEntityType.file) continue;

      final tombstone = File(
        _childPath(directory.path, '.$assetId.${_nextRandomId()}.deleting'),
      );
      await target.rename(tombstone.path);
      try {
        await tombstone.delete();
      } on Object {
        final targetType = await FileSystemEntity.type(
          target.path,
          followLinks: false,
        );
        if (targetType == FileSystemEntityType.notFound) {
          await tombstone.rename(target.path);
        }
        rethrow;
      }
      deleted = true;
    }
    return deleted;
  }

  Future<_ResolvedMedia?> _resolve({
    required String documentId,
    required Uri uri,
  }) async {
    final assetId = DocumentMediaUri.assetId(uri);
    if (assetId == null) return null;
    final normalizedDocumentId = _normalizeDocumentId(documentId);
    final directory = await _existingMediaDirectory(normalizedDocumentId);
    if (directory == null) return null;

    for (final format in _imageFormats) {
      final file = File(
        _childPath(directory.path, '$assetId.${format.extension}'),
      );
      if (await FileSystemEntity.type(file.path, followLinks: false) !=
          FileSystemEntityType.file) {
        continue;
      }
      final byteLength = await file.length();
      if (byteLength <= 0 || byteLength > maximumImageBytes) return null;
      final bytes = await file.readAsBytes();
      if (bytes.length != byteLength || bytes.length > maximumImageBytes) {
        return null;
      }
      if (_formatForBytes(bytes) != format) return null;

      return _ResolvedMedia(
        file: file,
        bytes: bytes,
        asset: LocalDocumentMediaAsset(
          documentId: normalizedDocumentId,
          assetId: assetId,
          uri: uri,
          mimeType: format.mimeType,
          extension: format.extension,
          byteLength: bytes.length,
        ),
      );
    }
    return null;
  }

  Future<Directory> _ensureMediaDirectory(String documentId) async {
    final directory = await _mediaDirectory(documentId);
    final type = await FileSystemEntity.type(
      directory.path,
      followLinks: false,
    );
    if (type == FileSystemEntityType.directory) return directory;
    if (type != FileSystemEntityType.notFound) {
      throw const LocalDocumentMediaException(
        'The local media directory is invalid.',
      );
    }
    await directory.create(recursive: true);
    if (await FileSystemEntity.type(directory.path, followLinks: false) !=
        FileSystemEntityType.directory) {
      throw const LocalDocumentMediaException(
        'Could not create local media storage.',
      );
    }
    return directory;
  }

  Future<Directory?> _existingMediaDirectory(String documentId) async {
    final directory = await _mediaDirectory(documentId);
    return await FileSystemEntity.type(directory.path, followLinks: false) ==
            FileSystemEntityType.directory
        ? directory
        : null;
  }

  Future<Directory> _mediaDirectory(String documentId) async {
    final support = await _supportDirectory();
    return Directory(
      _childPath(
        _childPath(_childPath(support.path, 'documents'), 'media'),
        _directoryNameForDocument(documentId),
      ),
    );
  }

  _ImageFormat _validateImport({
    required Uint8List bytes,
    required String fileName,
    required String? mimeType,
  }) {
    if (bytes.isEmpty) {
      throw const LocalDocumentMediaException('The selected image is empty.');
    }
    if (bytes.length > maximumImageBytes) {
      throw LocalDocumentMediaException(
        'The selected image exceeds the $maximumImageBytes-byte limit.',
      );
    }

    final extension = _extensionForFileName(fileName);
    final extensionFormat = _formatForExtension(extension);
    if (extensionFormat == null) {
      throw const LocalDocumentMediaException(
        'Only PNG, JPEG, GIF, and WebP image files are supported.',
      );
    }
    final detectedFormat = _formatForBytes(bytes);
    if (detectedFormat == null) {
      throw const LocalDocumentMediaException(
        'The selected file is not a supported image.',
      );
    }
    if (detectedFormat != extensionFormat) {
      throw const LocalDocumentMediaException(
        'The image file extension does not match its content.',
      );
    }

    if (mimeType != null) {
      final declaredFormat = _formatForMimeType(_normalizeMimeType(mimeType));
      if (declaredFormat == null || declaredFormat != detectedFormat) {
        throw const LocalDocumentMediaException(
          'The image MIME type does not match its content.',
        );
      }
    }
    return detectedFormat;
  }

  String _nextAssetId() {
    final generated = assetIdGenerator?.call() ?? _nextRandomId();
    if (!_assetIdPattern.hasMatch(generated)) {
      throw const LocalDocumentMediaException(
        'The generated image identifier is invalid.',
      );
    }
    return generated;
  }

  String _nextRandomId() {
    final random = Random.secure();
    final bytes = Uint8List(18);
    for (var index = 0; index < bytes.length; index += 1) {
      bytes[index] = random.nextInt(256);
    }
    return base64Url.encode(bytes).replaceAll('=', '');
  }

  static String _normalizeDocumentId(String value) {
    if (value.trim().isEmpty) {
      throw const LocalDocumentMediaException(
        'A document identifier is required.',
      );
    }
    if (utf8.encode(value).length > _maximumDocumentIdBytes) {
      throw const LocalDocumentMediaException(
        'The document identifier is too long.',
      );
    }
    return value;
  }

  static String _directoryNameForDocument(String documentId) =>
      base64Url.encode(utf8.encode(documentId)).replaceAll('=', '');

  static String _fileNameForPath(String path) {
    final separatorIndex = max(path.lastIndexOf('/'), path.lastIndexOf('\\'));
    return path.substring(separatorIndex + 1);
  }

  static String _childPath(String parent, String name) =>
      '$parent${Platform.pathSeparator}$name';

  static String _extensionForFileName(String value) {
    final fileName = _fileNameForPath(value.trim());
    final dot = fileName.lastIndexOf('.');
    if (dot <= 0 || dot == fileName.length - 1) return '';
    return fileName.substring(dot + 1).toLowerCase();
  }

  static _ImageFormat? _formatForExtension(String extension) {
    if (extension == 'jpeg') return _imageFormats[1];
    for (final format in _imageFormats) {
      if (format.extension == extension) return format;
    }
    return null;
  }

  static _ImageFormat? _formatForMimeType(String mimeType) {
    for (final format in _imageFormats) {
      if (format.mimeType == mimeType) return format;
    }
    return null;
  }

  static String _normalizeMimeType(String value) =>
      value.split(';').first.trim().toLowerCase();

  static _ImageFormat? _formatForBytes(Uint8List bytes) {
    if (_matches(bytes, const <int>[137, 80, 78, 71, 13, 10, 26, 10])) {
      return _imageFormats[0];
    }
    if (_matches(bytes, const <int>[255, 216, 255])) return _imageFormats[1];
    if (_matches(bytes, const <int>[71, 73, 70, 56, 55, 97]) ||
        _matches(bytes, const <int>[71, 73, 70, 56, 57, 97])) {
      return _imageFormats[2];
    }
    if (_matches(bytes, const <int>[82, 73, 70, 70]) &&
        bytes.length >= 12 &&
        bytes[8] == 87 &&
        bytes[9] == 69 &&
        bytes[10] == 66 &&
        bytes[11] == 80) {
      return _imageFormats[3];
    }
    return null;
  }

  static bool _matches(Uint8List value, List<int> signature) {
    if (value.length < signature.length) return false;
    for (var index = 0; index < signature.length; index += 1) {
      if (value[index] != signature[index]) return false;
    }
    return true;
  }
}

final class _ImageFormat {
  const _ImageFormat({required this.extension, required this.mimeType});

  final String extension;
  final String mimeType;
}

final class _ResolvedMedia {
  const _ResolvedMedia({
    required this.file,
    required this.bytes,
    required this.asset,
  });

  final File file;
  final Uint8List bytes;
  final LocalDocumentMediaAsset asset;
}
