import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

import '../../tool/quality_gate.dart';

const _validLock = '''# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  collection:
    dependency: transitive
    description:
      name: collection
      sha256: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
      url: "https://pub.dev"
    source: hosted
    version: "1.0.0"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  jpush_flutter:
    dependency: "direct main"
    description:
      path: "vendor/jpush_flutter"
      relative: true
    source: path
    version: "3.3.3"
sdks:
  dart: ">=3.12.0 <4.0.0"
  flutter: ">=3.44.0"
''';

void main() {
  test('accepts the pinned offline workspace lock policy', () {
    expect(dependencyPolicyFindings(_validLock), isEmpty);
  });

  test('rejects Git and unapproved path dependencies', () {
    final git = _validLock.replaceFirst('source: hosted', 'source: git');
    final path = _validLock
        .replaceFirst('jpush_flutter:', 'local_plugin:')
        .replaceFirst('vendor/jpush_flutter', '../local_plugin');

    expect(
      dependencyPolicyFindings(git),
      contains(contains('forbidden dependency source `git`')),
    );
    expect(
      dependencyPolicyFindings(path),
      contains(contains('not the approved vendor/jpush_flutter')),
    );
  });

  test('rejects untrusted hosted artifacts and missing integrity', () {
    final untrusted = _validLock
        .replaceFirst('https://pub.dev', 'https://packages.example.com')
        .replaceFirst(
          '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef',
          'not-a-sha',
        );
    final findings = dependencyPolicyFindings(untrusted);

    expect(findings, contains(contains('must use https://pub.dev')));
    expect(findings, contains(contains('64-character SHA-256')));
  });

  test('rejects retired packages and SDK policy drift', () {
    final drifted = _validLock
        .replaceFirst('collection:', 'ordered_set:')
        .replaceFirst('>=3.12.0 <4.0.0', '>=3.13.0 <4.0.0')
        .replaceFirst('>=3.44.0', '>=3.45.0');
    final findings = dependencyPolicyFindings(drifted);

    expect(findings, contains(contains('retired dependency')));
    expect(findings, contains(contains('Dart SDK policy')));
    expect(findings, contains(contains('Flutter SDK policy')));
  });

  test('requires one workspace lock and rejects nested member locks', () {
    expect(
      dependencyLockLayoutFindings(const <String>[
        'pubspec.lock',
        'src/pubspec.lock',
        r'packages\huahuo_api\pubspec.lock',
      ]),
      containsAll(<String>[
        'nested lock file is forbidden: src/pubspec.lock',
        'nested lock file is forbidden: packages/huahuo_api/pubspec.lock',
      ]),
    );
    expect(dependencyLockLayoutFindings(const <String>[]), <String>[
      'workspace pubspec.lock is missing',
    ]);
  });

  test('includes product package and contract parity gates', () {
    final steps = qualityGateStepDisplays(Directory.current.path);

    expect(steps.first, startsWith('format workspace:dart format'));
    expect(steps, contains(startsWith('analyze huahuo_product:')));
    expect(
      steps,
      contains(
        'API contract consistency:dart run tool/api_contract_consistency_check.dart',
      ),
    );
    expect(
      steps,
      contains('feature parity:dart run tool/feature_parity_check.dart'),
    );
    expect(steps, contains('test huahuo_product:dart test'));
    expect(steps, contains('test huahuo_foundation:flutter test --no-pub'));
    expect(steps.where((step) => step.startsWith('test ')), hasLength(6));
    expect(steps.first, contains('packages/huahuo_foundation/test'));
    expect(steps.first, contains('src/integration_test'));
    expect(steps.first, contains('src/test_driver'));
    expect(
      steps,
      contains(
        'API contract consistency:dart run tool/api_contract_consistency_check.dart',
      ),
    );
  });
}
